/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appempregados;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author afonsvfdeb
 */
public class ConsultarEmpregado extends javax.swing.JInternalFrame {
    
    Empregado[] empregados = new Empregado[10];    
    
    /**
     * Creates new form ConsultarEmpregado
     */
    public ConsultarEmpregado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JRtodos = new javax.swing.JRadioButton();
        JRclt = new javax.swing.JRadioButton();
        JRhorista = new javax.swing.JRadioButton();
        jBconsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        buttonGroup1.add(JRtodos);
        JRtodos.setSelected(true);
        JRtodos.setText("Todos");
        JRtodos.addActionListener(this::JRtodosActionPerformed);

        buttonGroup1.add(JRclt);
        JRclt.setText("CLT");
        JRclt.addChangeListener(this::JRcltStateChanged);
        JRclt.addActionListener(this::JRcltActionPerformed);

        buttonGroup1.add(JRhorista);
        JRhorista.setText("Horista");

        jBconsultar.setText("Consultar");
        jBconsultar.addActionListener(this::jBconsultarActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Endereco", "Salario Liquido", "Nhoras", "Preco hora"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBconsultar)
                    .addComponent(JRhorista)
                    .addComponent(JRtodos)
                    .addComponent(JRclt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(JRtodos)
                .addGap(18, 18, 18)
                .addComponent(JRclt)
                .addGap(18, 18, 18)
                .addComponent(JRhorista)
                .addGap(18, 18, 18)
                .addComponent(jBconsultar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JRtodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRtodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRtodosActionPerformed

    private void JRcltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRcltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRcltActionPerformed

    private void jBconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultarActionPerformed
        // TODO add your handling code here:
        
        //criar um objeto da classe main
        
        MainForm acoes = new MainForm();
        
        //atualizar a lista de empregados
        
        empregados = acoes.getEmpregados(); //pega os empregados da classe MainForm
        //atualizar o valor de index
        
        Integer index = acoes.getIndex();
        
        //criando um metodo jtable no codigo
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        //limpar as linhas do jtable
        
        model.setRowCount(0);
        
         //Estrutura de repetição para imprimir os Empregados
         //ADAPTANDO PARA INTERFACE GRAFICA
        for(int count = 0 ;count<index;count++)
        {
           
           if(JRtodos.isSelected()){
            model.addRow(new Object[]{empregados[count].getNome(), 
                empregados[count].getCpf(),
                empregados[count].getEndereco(), 
                empregados[count] instanceof EmpregadoCLT ? ((EmpregadoCLT)empregados[count]).getsBruto() : ((EmpregadoHorista)empregados[count]).salarioHorista() });
                          
           }else if(JRclt.isSelected()){
               
               if(empregados[count] instanceof EmpregadoCLT){
                  model.addRow(new Object[]{ 
                      ((EmpregadoCLT) empregados[count]).getNome(),
                      ((EmpregadoCLT) empregados[count]).getCpf(),
                      ((EmpregadoCLT) empregados[count]).getEndereco(),
                      ((EmpregadoCLT) empregados[count]).salarioLiquidoCLT()
                  });
               }
           
           }else{
               
               if(empregados[count] instanceof EmpregadoHorista){
                  model.addRow(new Object[]{ 
                      ((EmpregadoHorista) empregados[count]).getNome(),
                      ((EmpregadoHorista) empregados[count]).getCpf(),
                      ((EmpregadoHorista) empregados[count]).getEndereco(),
                      ((EmpregadoHorista) empregados[count]).salarioHorista(),
                      ((EmpregadoHorista) empregados[count]).getnHoras(),
                      ((EmpregadoHorista) empregados[count]).getPrecoHora()
                  });
               }              
               
           }
            
            
            
            
            
            
            
            //Imprimindo dados gerais de cada empregado
            System.out.println("Nome:"+empregados[count].getNome());
            System.out.println("CPF:"+empregados[count].getCpf());
            System.out.println("Endereço:"+empregados[count].getEndereco());
            //Como as informações não são genéricas temos que verificar qual é o tipo
            //do objeto da lista: CLT ou Horista
            if(empregados[count]instanceof EmpregadoCLT){ //se for EmpregadoCLT então imprime
                //Imprimindo o Salario bruto e o Salario Líquido
                System.out.println("Salário Bruto:");
                EmpregadoCLT temp = (EmpregadoCLT)(empregados[count]); //Cast para deixar os dados compativeis
                System.out.print(temp.getsBruto());
                System.out.println("Salário Líquido:"+temp.salarioLiquidoCLT());     
            }
            //Verificando se é horista
            if(empregados[count]instanceof EmpregadoHorista){ //se for Horista então imprime
            //Imprimindo o Salario bruto e o Salario Líquido
            EmpregadoHorista temp = (EmpregadoHorista)(empregados[count]); //Cast para deixar os dados compativeis
            System.out.println("Número de Horas:"+temp.getnHoras());
            System.out.println("Preço das Horas:"+temp.getPrecoHora()); 
            System.out.println("Salário Líquido:"+temp.salarioHorista());
        }  
       }
        
    }//GEN-LAST:event_jBconsultarActionPerformed

    private void JRcltStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_JRcltStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_JRcltStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRclt;
    private javax.swing.JRadioButton JRhorista;
    private javax.swing.JRadioButton JRtodos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBconsultar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
